### ISSUE TITLE
error when starting kibana after install

### ISSUE THREAD

**Issue by ghost** [robcowart/kibana-vis-dropdown#1]
Hi,

I just did the installation of the plugin, i changed the version in the json files to my version 5.6.3.
when starting kibana, i get the following fatal error:

FATAL Error: Config schema already has key: kibana_dropdown
    at Config.extendSchema (/usr/share/kibana/src/server/config/config.js:51:13)
    at /usr/share/kibana/src/server/plugins/plugin_collection.js:19:12
    at next (native)
    at step (/usr/share/kibana/src/server/plugins/plugin_collection.js:49:191)
    at /usr/share/kibana/src/server/plugins/plugin_collection.js:49:361

Do you know how to fix this?

**Comment by ghost** [comment]
Fixed by removing pre-existing dropdown plugin from other git repo in the plugin folder.
